# Generated by Django 3.2.5 on 2022-09-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220813_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
    ]
