# Generated by Django 3.2.5 on 2022-08-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_pool_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
