# Generated by Django 3.2.5 on 2022-09-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
