# Generated by Django 3.2.5 on 2022-08-09 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='listclient',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Lista de cliente', 'verbose_name_plural': 'Lista de clientes'},
        ),
        migrations.RemoveField(
            model_name='listclient',
            name='client',
        ),
        migrations.CreateModel(
            name='ListItemClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='campaign.client')),
                ('list_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_client', to='campaign.listclient')),
            ],
            options={
                'verbose_name': 'Item de lista de cliente',
                'verbose_name_plural': 'ListItemClients',
                'ordering': ('-updated_at',),
            },
        ),
    ]
