# Generated by Django 3.2.5 on 2022-08-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_token'),
        ('campaign', '0004_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_campaigns', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_clients', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listclient',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_list_client', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitemclient',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_items', to='company.company'),
            preserve_default=False,
        ),
    ]
