# Generated by Django 3.2.5 on 2022-08-12 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_token'),
        ('campaign', '0005_auto_20220812_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nuevo contacto', 'Lead'), ('cliente', 'Client')], default='nuevo contacto', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contact', to='company.company')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ListContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_list_contact', to='company.company')),
            ],
            options={
                'verbose_name': 'Lista de contacto',
                'verbose_name_plural': 'Lista de contactos',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ListItemContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_item_list', to='company.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='campaign.contact')),
                ('list_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_contact', to='campaign.listcontact')),
            ],
            options={
                'verbose_name': 'item de contacto ',
                'verbose_name_plural': 'items de contactos ',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.RemoveField(
            model_name='listclient',
            name='company',
        ),
        migrations.RemoveField(
            model_name='listitemclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='listitemclient',
            name='company',
        ),
        migrations.RemoveField(
            model_name='listitemclient',
            name='list_client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ListClient',
        ),
        migrations.DeleteModel(
            name='ListItemClient',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='list_client',
            field=models.ManyToManyField(blank=True, related_name='roster', to='campaign.ListContact'),
        ),
    ]
