# Generated by Django 3.2.5 on 2022-08-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20220812_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='list_client',
            new_name='list_contact',
        ),
    ]
